添加文档
dotnet-campus/dotnetCampus.CommandLineArgsViewer pull request #3
Opened 2020-07-18 02:10 UTC by lindexi

2020-07-18 03:06 UTC, walterlv requested changes

2020-07-18 03:06 UTC, walterlv commented on README.md
> +This tool is used to observe that the parameters of the incoming command line are as expected.
You can view all the arguments passed from shells to this tool which helps you to debug command-lines.

要点：
* parameter 形参，argument 实参
* command line 单词应该加 `-`

2020-07-18 03:06 UTC, walterlv commented on README.md
> +- Observe the count of the arguaments.
```suggestion
- View the count of the arguments.
```

要点：
* Observe 观察，View 查看
* argument 单词拼写错误

2020-07-18 03:06 UTC, walterlv commented on README.md
> +- The character that is escaped.
```suggestion
- The characters which are escaped.
```

要点：
* 复数
* that 带从句，which 修饰定语

2020-07-18 03:06 UTC, walterlv commented on README.md
> +- The difference between Kernal32 and .NET
```suggestion
- View the command line loss from the shells (e.g. PowerShell lost quotes comparing to CMD).
- View the command line loss of the .NET version comparing with the Kernel32 version.
```

要点：
* Kernel32 拼写错误
* 同时说明了为什么要比较区别，比较的是哪一层的区别

2020-07-18 03:06 UTC, walterlv commented on README.md
> +Input the arguments after ShowArgs, and you will find what is the application actually received arguments.
```suggestion
Type any arguments after the command `ShowArgs`, and you'll view the command-line and args that an app (or a .NET app) will actually receive.
```

要点：
* 时态混乱

2020-07-18 03:06 UTC, walterlv commented on README.md
> +
````suggestion
```
ShowArgs [args]
```

For example, you can type the command line below:

```
ShowArgs /select,"D:\1,1.txt"
```

````

2020-07-18 06:24 UTC, walterlv requested changes

2020-07-18 06:24 UTC, walterlv commented on README.md
> +You can view all the arguments passed from shells to this tool which helps you to debug command-lines.
This is a tool to debug command-lines that you can view all the arguments passed from shells.

2020-07-18 06:24 UTC, walterlv commented on README.md
> +- View the command line loss of the .NET version comparing with the Kernel32 version.
好像你少了一行，再看看上面提的问题？

2020-07-18 06:24 UTC, walterlv commented on README.md
> +- The characters which are escaped.
View the shell escaping behavior of any characters (quote etc.)

2020-07-18 06:24 UTC, walterlv commented on docs/zh-cn/README.md
> +用来查看经过了 Shell 传入此应用的命令行，此工具用来调试命令行参数
此工具用来调试命令行参数，可查看经过了不同种类的 Shell 传入此应用的命令行

2020-07-18 06:24 UTC, walterlv commented on docs/zh-cn/README.md
> +|![](https://github.com/dotnet-campus/dotnetCampus.CommandLineArgsViewer/workflows/.NET%20Core/badge.svg)|[![](https://img.shields.io/nuget/v/dotnetCampus.CommandLineArgsViewer.svg)](https://www.nuge
仅首页放状态就好了，其他页安心放说明文档。

2020-07-18 06:24 UTC, walterlv commented on docs/zh-cn/README.md
> +- 查看命令行参数数量，用于调试是否有一个参数被分割为多个等
```suggestion
- 查看命令行参数数量，用于调试是否有一个参数被分割为多个或多个参数被合并为一个等
```

2020-07-18 06:24 UTC, walterlv commented on docs/zh-cn/README.md
> +- 对比 Kernel32 和 .NET 收到的参数的不同
```suggestion
- 对比不同种类 Shell 传入到应用程序中参数的不同
- 对比 Kernel32 方式和 .NET 方式收到的参数的不同
```

2020-07-18 06:24 UTC, walterlv commented on docs/zh-cn/README.md
> +作为 dotnet 全局工具安装
```suggestion
作为 dotnet 全局工具安装。
```

2020-07-18 06:24 UTC, walterlv commented on docs/zh-cn/README.md
> +在 `ShowArgs` 命令之后输出需要调试的参数，此时命令行将会输出在应用里面实际收到的参数
```suggestion
在 `ShowArgs` 命令之后输出需要调试的参数，此时命令行将会输出在应用里面实际收到的参数。
```

2020-07-18 06:24 UTC, walterlv commented on docs/zh-cn/README.md
> +例如，输入如下参数
```suggestion
例如，在 PowerShell 和 CMD 中输入如下参数，可以得到引号在这两种 Shell 中的不同行为。
```

2020-07-20 08:26 UTC, kkwpsv commented
我来替 @walterlv 做这个没良心的人。。

2020-07-20 08:26 UTC, merged